language: node_js
node_js: '8'
before_install:
  - npm install @lampix/core@0.x
deploy:
  provider: npm
  email: dbalaban@lampix.co
  api_key:
    secure: IWN+vWVuqMwO0vfHwvrzIUq3h3uIYtT++89iP44ee53ARgRKG9UXwZhqtjfJrbC8RRcKp2A7NS+x2qGBbKwKCll6j0nQ0vqQVNUYh+OBOSWPWUP8fa9kBlaIL9qisHCo5QY75435YQWndVXYVo/w6Q+HEoacXhG8sV4lrgbf+FQxu3ZZ4a468d24SH8YiShCGnXQej/kQYii3kgqjq08ivpj/fN0z8XSqYoByhZ9HlsEXMM+qxu+5ubz5/Jt464eR9ZPdhpHKQe0HhdHNXGpE851Rk3uUXonPhM0zFv3e16Y7UZXHVi7nDLiYEZe+yo08bdF+go0ayCeZEBhQeafZMe8WaCz4ihrWHKACMPRxL40fD+/SJOUyk2kDDiW6fiUfvQDuGYwTvwc+R8eAcI3k4xCcGrI5xCA3Pdw8w1am+t7mzgWoqGrKzYJHOlYupEnziUza26sLfpIkQhUJUJvyYZNKaqcVJMX//qDn5H3fWZhOF0SRiZUei1ZCKWgnbR6+nkHMuIomqzueve1vKdlP3k8Wn2pAC94EESKtAlRogPDydlnYWeUaqeYHosKH3YzqCr9pCVV+pjt/+/fopBSTFXU/CVSP+kpXTP66s0zBuOrj7NEkRYRyuBuO6NBn/8YKknYxN3W6dRgw77spR0dd/0aN5MX98LuOagec3rOhhE=
  skip_cleanup: true
  on:
    repo: lampix-org/lampixjs-state
    all_branches: true
branches:
  only:
    - "/^release\\/\\d+\\.\\d+\\.\\d+$/"
